CREATE DATABASE LIBRARY;  -- DATABASE NAME
USE LIBRARY;  -- DATABASE ISTIFADE ETMEK 

CREATE TABLE USERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (255) NOT NULL,
SURNAME NVARCHAR (255),
EMAIL NVARCHAR(100) UNIQUE,
MOBILNUMBER INT,
PHONENUMBER INT,
ADMITT DATE,
[STATUS] BIT,
[LEVEL] BIT,
DELETED BIT
)

ALTER TABLE USERS ADD [PASSWORD] VARCHAR(255) ;

SELECT * FROM USERS

ALTER TABLE ORDERS ADD DELEVERYBOOK BIT ;
ALTER TABLE ORDERS ADD BOOKCOUNT INT ;

CREATE TABLE ORDERS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERORDERDATE DATE,
DELIVARYORDERDATE DATE,
CUSTOMERID INT REFERENCES CUSTOMER(ID),
BOOKSID INT REFERENCES BOOKS(ID),
USERSID INT REFERENCES USERS(ID) 
)


ALTER TABLE CUSTOMER ADD DELETED BIT ;

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY IDENTITY,
CUSTNAME NVARCHAR(255),
CUSTSURNAME NVARCHAR(255),
MOBIL NVARCHAR (30),
IDENTITYCARDNUMBER NVARCHAR(100),
[ADDRESS] NVARCHAR (255)
)

ALTER TABLE BOOKS ADD DELETED BIT ;

ALTER TABLE BOOKS ADD PRICE float ;
ALTER TABLE BOOKS ADD Punish float ;
CREATE TABLE BOOKS(
ID INT PRIMARY KEY IDENTITY,
BOOKNAME NVARCHAR(255),
BOOKTYPE NVARCHAR(255),
AUTHOR NVARCHAR(255),
BOOKCOUNT INT
)

select * from BOOKS;

select * from USERS;

Select * from ORDERS;

Select * from CUSTOMER;